/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OraoVRFConsumer__factory } from "./OraoVRFConsumer__factory";
export { OraoVRFConsumerFail__factory } from "./OraoVRFConsumerFail__factory";
