/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { IZK, IZKInterface } from "../../../contracts/interfaces/IZK";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "X",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "Y",
                type: "uint256",
              },
            ],
            internalType: "struct IZK.G1Point",
            name: "a",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "X",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2]",
                name: "Y",
                type: "uint256[2]",
              },
            ],
            internalType: "struct IZK.G2Point",
            name: "b",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "X",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "Y",
                type: "uint256",
              },
            ],
            internalType: "struct IZK.G1Point",
            name: "c",
            type: "tuple",
          },
        ],
        internalType: "struct IZK.Proof",
        name: "proof",
        type: "tuple",
      },
      {
        internalType: "uint256[12]",
        name: "input",
        type: "uint256[12]",
      },
    ],
    name: "verifyTx",
    outputs: [
      {
        internalType: "bool",
        name: "r",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZK__factory {
  static readonly abi = _abi;
  static createInterface(): IZKInterface {
    return new utils.Interface(_abi) as IZKInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IZK {
    return new Contract(address, _abi, signerOrProvider) as IZK;
  }
}
