/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OraoVRFConsumer } from "./OraoVRFConsumer";
export type { OraoVRFConsumerFail } from "./OraoVRFConsumerFail";
